# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^worker-configuration.d.ts$
      - id: end-of-file-fixer
        exclude: ^worker-configuration.d.ts$
      - id: check-json
        exclude: ^tsconfig.json$

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.8.1
    hooks:
      - id: prettier
        types: [ ts ]
        exclude: ^worker-configuration.d.ts$

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.3.0
    hooks:
      - id: doctoc
        args: [ --title, '**Table of Contents**' ]
        files: ^(CHANGELOG|README).md$

  - repo: local
    hooks:
      - id: wrangler-types
        name: Regenerate wrangler types
        language: unsupported
        entry: wrangler types
        files: ^package.json|wrangler.toml$
        pass_filenames: false
        require_serial: true
