name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # 7.0.1

      - name: Publish hnkrocks-router to Cloudflare
        uses: cloudflare/wrangler-action@953926a2e2182532811c01a25e53647d93bf07c0  # 4.1.3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
