name: Deploy to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # 6.0.2

      - name: Publish hnkrocks-router to Cloudflare
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd  # 3.15.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: 4.86.0
